# Generated by Django 3.0.5 on 2020-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20200504_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ManyToManyField(related_name='vehicle', to='orm.Customer'),
        ),
    ]
