# Generated by Django 3.0.5 on 2020-04-29 08:38

import bootstr.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('featured_image', models.FileField(upload_to='static/images/%Y/%m/%d', validators=[bootstr.validators.validate_file_extension])),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
